Birth_date:
  cde: Birthdate
  columns:
    pid: patient_id
    value: birthdate
    startdate: birthdate
    # enddate: birthdate
    event_id: birthdate-context
    
Birth_year:
  cde: Birthyear
  columns:
    pid: patient_id
    value: birthyear
    # startdate: birthdate
    # enddate: birthdate
    event_id: birthdate-context

# Education:
#   cde: Questionnaire
#   columns:
#     pid: patient_id
#     value: education
#     activity: education-url
#     startdate: symptom-date
#     # enddate: symptom-date
#     event_id: symptom-date-context
    

Sex:
  cde: Sex
  columns:
    pid: patient_id
    valueIRI: sex
    startdate: birthdate
    # enddate: birthdate
    event_id: birthdate-context


# Status:
#   cde: Status
#   columns:
#     pid: patient_id
#     valueIRI: status
#     startdate: status-date
#     # enddate: status-date
#     event_id: status-date-context
    

# Date_of_death:
#   cde: Deathdate
#   columns:
#     pid: patient_id
#     value: deathdate
#     startdate: status-date
#     # enddate: status-date
#     event_id: status-date-context
    

# Care_pathway:
#   cde: First_visit
#   columns:
#     pid: patient_id
#     value: first-confirmed-visit
#     startdate: first-confirmed-visit
#     # enddate: first-confirmed-visit
#     event_id: first-confirmed-visit-context
   

symptomHematuria:
  cde: Symptom
  columns:
    pid: patient_id
    valueIRI: symptom-hematuria
    startdate: symptom-date
    # enddate: symptom-date
    event_id: symptom-date-context
    

symptomVasculitis:
  cde: Symptom
  columns:
    pid: patient_id
    valueIRI: symptom-vasculitis
    startdate: symptom-date
    # enddate: symptom-date
    event_id: symptom-date-context



symptomCystinuria:
  cde: Symptom
  columns:
    pid: patient_id
    valueIRI: symptom-cystinuria
    startdate: symptom-date
    # enddate: symptom-date
    event_id: symptom-date-context

    
symptomOnset:
  cde: Questionnaire
  columns:
    pid: patient_id
    value: date-onset
    activity: onset-url
    target: symptom-cystinuria
    value_datatype: datatype
    startdate: symptom-date
    # enddate: symptom-date
    event_id: symptom-date-context
   


# Consent_clinical:
#   cde: Consent_used
#   columns:
#     pid: patient_id
#     value: consent-used
#     startdate: consent-date
#     # enddate: consent-date
#     event_id: consent-date-context
  

# Consent_research:
#   cde: Consent_contacted
#   columns:
#     pid: patient_id
#     value: consent-reseach
#     startdate: consent-date
#     # enddate: consent-date
#     event_id: consent-date-context
    

Genotype_OMIM:
  cde: Genetic
  columns:
    pid: patient_id
    valueIRI: variant-id
    value: variant-value
    target: omim-id
    startdate: consent-date
    # enddate: consent-date
    event_id: consent-date-context


# Genotype_zygosity:
#   cde: Zygosity
#   columns:
#     pid: patient_id
#     valueIRI: zygosity
#     target: variant-id
#     startdate: consent-date
#     # enddate: consent-date
#     event_id: consent-date-context


# Genotype_aminoacid:
#   cde: Aminoacid
#   columns:
#     pid: patient_id
#     valueIRI: protein
#     value: aminoacid-pos
#     target: aminoacid
#     startdate: consent-date
#     # enddate: consent-date
#     event_id: consent-date-context
    

# Disability:
#   cde: Questionnaire
#   columns:
#     pid: patient_id
#     value: disability-score
#     activity: disability-type
#     startdate: symptom-date
#     # enddate: symptom-date
#     event_id: symptom-date-context
    

# Biobank:
#   cde: Biobank
#   columns:
#     pid: patient_id
#     agent: biobank-id
#     startdate: consent-date
#     # enddate: consent-date
#     event_id: consent-date-context
    

# Lab_homocysteine:
#   cde: Lab_measurement
#   columns:
#     pid: patient_id
#     input: input-lab
#     value: lab-value
#     target: target-lab
#     unit: unit-lab
#     startdate: lab-date
#     # enddate: lab-date
#     event_id: lab-date-context

Diagnosis-acidemia:
  cde: Diagnosis
  columns:
    pid: patient_id
    valueIRI: diagnosis-homocisteruria
    startdate: diagnosis-date
    # enddate: diagnosis-date
    event_id: diagnosis-date-context    

Diagnosis-other:
  cde: Diagnosis
  columns:
    pid: patient_id
    valueIRI: diagnosis-other
    startdate: diagnosis-date
    # enddate: diagnosis-date
    event_id: diagnosis-date-context    
    

# UltrasoundKidney:
#   cde: Imaging
#   columns:
#     pid: patient_id
#     valueIRI: imaging-id
#     activity: imaging-process
#     target: imaging-target
#     startdate: imaging-date
#     # enddate: imaging-date
#     event_id: imaging-date-context
    

# BMI:
#   cde: Body_measurement
#   columns:
#     pid: patient_id
#     valueIRI: bmi
#     value: bmi-value
#     startdate: body-measurement-date
#     # enddate: body-measurement-date
#     event_id: body-measurement-date-context

# Biopsy:
#   cde: Surgery
#   columns:
#     pid: patient_id
#     activity: skin-biopsy
#     target: target-biopsy
#     startdate: biopsy-date
#     # enddate: biopsy-date
#     event_id: biopsy-date-context

# Med:
#   cde: Medication
#   columns:
#     pid: patient_id
#     value: dose_value
#     unit: unit_type
#     frequency_type: freq_type
#     frequency_value: frequency_value
#     route: route
#     agent: drug_used
#     startdate: medication-date
#     # enddate: medication-date
#     event_id: medication-date-context