Birth_date:
  cde: Birthdate
  columns:
    pid: patient_id
    value: birthdate
    startdate: birthdate
    enddate: birthdate
    event_id: birthdate-context
    protocol_id: protocol
    

# Birthyear:
#   cde: Birthyear
#   columns:
#     pid: patient_id
#     value: birthyear
#     startdate: birthdate
#     enddate: birthdate
    

Sex:
  cde: Sex
  columns:
    pid: patient_id
    valueIRI: sex
    startdate: birthdate
    enddate: birthdate
    event_id: birthdate-context
    protocol_id: protocol
    


Status:
  cde: Status
  columns:
    pid: patient_id
    valueIRI: status
    startdate: status-date
    enddate: status-date
    event_id: status-date-context
    protocol_id: protocol
    

Date_of_death:
  cde: Deathdate
  columns:
    pid: patient_id
    value: deathdate
    startdate: status-date
    enddate: status-date
    event_id: status-date-context
    protocol_id: protocol
    

Care_pathway:
  cde: First_visit
  columns:
    pid: patient_id
    value: first-confirmed-visit
    startdate: first-confirmed-visit
    enddate: first-confirmed-visit
    event_id: first-confirmed-visit-context
    protocol_id: protocol
   

symptomHematuria:
  cde: Symptom
  columns:
    pid: patient_id
    valueIRI: symptom-hematuria
    startdate: symptom-date
    enddate: symptom-date
    event_id: symptom-date-context
    protocol_id: protocol
    

symptomVasculitis:
  cde: Symptom
  columns:
    pid: patient_id
    valueIRI: symptom-vasculitis
    startdate: symptom-date
    enddate: symptom-date
    event_id: symptom-date-context
    protocol_id: protocol



symptomCystinuria:
  cde: Symptom
  columns:
    pid: patient_id
    valueIRI: symptom-cystinuria
    startdate: symptom-date
    enddate: symptom-date
    event_id: symptom-date-context
    protocol_id: protocol

    
symptomOnset:
  cde: Symptoms_onset
  columns:
    pid: patient_id
    value: date-onset
    startdate: symptom-date
    enddate: symptom-date
    event_id: symptom-date-context
    protocol_id: protocol
   


Consent_clinical:
  cde: Consent_used
  columns:
    pid: patient_id
    value: consent-used
    startdate: consent-date
    enddate: consent-date
    event_id: consent-date-context
    protocol_id: protocol
  

Consent_research:
  cde: Consent_contacted
  columns:
    pid: patient_id
    value: consent-reseach
    startdate: consent-date
    enddate: consent-date
    event_id: consent-date-context
    protocol_id: protocol
    

Genotype_OMIM:
  cde: Genetic
  columns:
    pid: patient_id
    valueIRI: variant-id
    value: variant-value
    target_type: omim-id
    startdate: consent-date
    enddate: consent-date
    event_id: consent-date-context
    protocol_id: protocol
    

Disability:
  cde: Questionnaire
  columns:
    pid: patient_id
    value: disability-score
    activity_type : disability-type
    startdate: symptom-date
    enddate: symptom-date
    event_id: symptom-date-context
    protocol_id: protocol
    

Biobank:
  cde: Biobank
  columns:
    pid: patient_id
    agent_id: biobank-id
    startdate: consent-date
    enddate: consent-date
    event_id: consent-date-context
    protocol_id: protocol
    

Lab_homocysteine:
  cde: Lab_measurement
  columns:
    pid: patient_id
    input_type: input-lab
    value: lab-value
    target_type: target-lab
    unit_type: unit-lab
    startdate: lab-date
    enddate: lab-date
    event_id: lab-date-context
    protocol_id: protocol

Diagnosis-acidemia:
  cde: Diagnosis
  columns:
    pid: patient_id
    valueIRI: diagnosis-homocisteruria
    startdate: diagnosis-date
    enddate: diagnosis-date
    event_id: diagnosis-date-context    
    protocol_id: protocol

Diagnosis-other:
  cde: Diagnosis
  columns:
    pid: patient_id
    valueIRI: diagnosis-other
    startdate: diagnosis-date
    enddate: diagnosis-date
    event_id: diagnosis-date-context    
    protocol_id: protocol
    

UltrasoundKidney:
  cde: Imaging
  columns:
    pid: patient_id
    valueIRI: imaging-id
    activity_type: imaging-process
    startdate: imaging-date
    enddate: imaging-date
    event_id: imaging-date-context
    protocol_id: protocol
    

BMI:
  cde: Body_measurement
  columns:
    pid: patient_id
    valueIRI: bmi
    value: bmi-value
    startdate: body-measurement-date
    enddate: body-measurement-date
    event_id: body-measurement-date-context
    protocol_id: protocol

Biopsy:
  cde: Surgery
  columns:
    pid: patient_id
    activity_type: skin-biopsy
    target_type: target-biopsy
    startdate: biopsy-date
    enddate: biopsy-date
    event_id: biopsy-date-context
    protocol_id: protocol

Med:
  cde: Medication
  columns:
    pid: patient_id
    value: dose_value
    unit_type: unit_type
    frequency_type: freq_type
    frequency_value: frequency_value
    route_type: route
    substance_id: drug_used
    startdate: medication-date
    enddate: medication-date
    event_id: medication-date-context
    protocol_id: protocol



